### ISSUE TITLE
dockerize the apps

### ISSUE THREAD

**Issue by kfarkasHU** [wraithlight/wraithlight-mono#13]
semi blocked by: https://github.com/wraithlight/wraithlight-mono/issues/820
* [x] auth https://github.com/wraithlight/wraithlight-mono/pull/926
* [x] content https://github.com/wraithlight/wraithlight-mono/pull/870
* [x] editor https://github.com/wraithlight/wraithlight-mono/pull/873
* [x] game-website https://github.com/wraithlight/wraithlight-mono/pull/874
* [x] logs https://github.com/wraithlight/wraithlight-mono/pull/875
* [x] notifier https://github.com/wraithlight/wraithlight-mono/pull/882
* [x] remote-config https://github.com/wraithlight/wraithlight-mono/pull/883
* [x] website https://github.com/wraithlight/wraithlight-mono/pull/884
