### ISSUE TITLE
blow up `core.types`

### ISSUE THREAD

**Issue by kfarkasHU** [wraithlight/wraithlight-mono#265]
Its unmaintainable right now, better to split smaller ones
In scope of this, populate this task with subtasks
Once all of these done, remove the given package for the next few years.

* [x] `core.boolean`
* [x] `core.counter`
* [x] `core.date`
* [x] `core.deepartial`
* [x] `core.dictionary`
* [x] `core.guid`
* [x] `core.nullable`
* [x] `core.random-number`
* [x] `core.random-string`
* [x] `core.predicate`
* [x] `core.primitive`
* [x] `core.undefined`
* [x] remove `core.types` - will be tracked in https://github.com/wraithlight/wraithlight-mono/issues/472
