### ISSUE TITLE
create service users

### ISSUE THREAD

**Issue by kfarkasHU** [wraithlight/wraithlight-mono#961]
There should be two service users:
* one what will be used when deploying the platform (platform_deployer_svc@wraithlight.ai)
* one what will be used when doing registering a new user (platform_onboarding_svc@wraithlight.ai)

---

* [x] (feat) Add these users to user management preseed
* [x] (docs) Document these users
* [x] (feat) Add onboarding svc user to user management constants

These users should not have login scopes by default.
